[package]
name = "cr8cert"
version = "0.1.0"
authors = ["Hyeonsu Lee <incleaf@gmail.com>"]

[dependencies]
clap = "2.32"
openssl = { version = "0.10", features = ["vendored"] }
pem = "0.4"
plist = "0.3"
